/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

/**
 *
 * @author JESSEN SALAYSAY
 */
public class Load extends javax.swing.JFrame {

    /**
     * Creates new form Load
     */
    public Load() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        backgroundPNL = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        signupBTN = new javax.swing.JButton();
        loginBTN = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        backgroundPNL.setBackground(new java.awt.Color(204, 204, 204));
        backgroundPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200blackLOGO.png"))); // NOI18N
        backgroundPNL.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 20, 160, 90));

        signupBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        signupBTN.setText("SIGN UP");
        signupBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                signupBTNActionPerformed(evt);
            }
        });
        backgroundPNL.add(signupBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(850, 40, -1, -1));

        loginBTN.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        loginBTN.setText("LOG IN");
        loginBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                loginBTNActionPerformed(evt);
            }
        });
        backgroundPNL.add(loginBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(1000, 40, -1, -1));

        getContentPane().add(backgroundPNL, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1150, 750));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void loginBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_loginBTNActionPerformed
        // Create a new instance of the Login frame
    Login loginFrame = new Login();
    
    // Set the current frame to be invisible (optional)
    this.setVisible(false);
    
    // Make the new Login frame visible
    loginFrame.setVisible(true);
    
    // Optionally, dispose of the current frame if you don't need it anymore
    // this.dispose();
    }//GEN-LAST:event_loginBTNActionPerformed

    private void signupBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_signupBTNActionPerformed
    Signup signupFrame = new Signup();
    this.setVisible(false);
    signupFrame.setVisible(true);
    }//GEN-LAST:event_signupBTNActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Load.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Load().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel backgroundPNL;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JButton loginBTN;
    private javax.swing.JButton signupBTN;
    // End of variables declaration//GEN-END:variables
}
