/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;
import dbConnection.DatabaseConnection;

import javax.swing.table.DefaultTableModel;
import java.sql.Connection;
import java.sql.Date;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import javax.swing.JOptionPane;


/**
 *
 * @author JESSEN SALAYSAY
 */
public class User extends javax.swing.JFrame {

    /**
     * Creates new form Admin
     */
    public User() {
        initComponents();
        loadSimpleBookingDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel6 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        logoutBTN = new javax.swing.JButton();
        logoLBL = new javax.swing.JLabel();
        dashboardBTN = new javax.swing.JButton();
        roomsBTN = new javax.swing.JButton();
        bookingBTN = new javax.swing.JButton();
        JTabbedPane = new javax.swing.JTabbedPane();
        dashboardPNL = new javax.swing.JPanel();
        jLabel11 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        bookingsPNL = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        endDateJcalendar = new de.wannawork.jcalendar.JCalendarComboBox();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        BookBTN = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        bookingTBL = new javax.swing.JTable();
        jLabel10 = new javax.swing.JLabel();
        startingdateJcalendar = new de.wannawork.jcalendar.JCalendarComboBox();
        searchTXT = new javax.swing.JTextField();
        roomNoTXT = new javax.swing.JTextField();
        roomTypeTXT = new javax.swing.JTextField();
        searchBtn = new javax.swing.JButton();
        updateBtn = new javax.swing.JButton();
        jLabel12 = new javax.swing.JLabel();
        roomsPNL = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        bg = new javax.swing.JLabel();

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel2.setBackground(new java.awt.Color(10, 61, 98));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        logoutBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        logoutBTN.setText("LOGOUT");
        logoutBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                logoutBTNActionPerformed(evt);
            }
        });
        jPanel2.add(logoutBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 480, 150, 40));

        logoLBL.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/200whiteLOGO.png"))); // NOI18N
        jPanel2.add(logoLBL, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 40, 170, -1));

        dashboardBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        dashboardBTN.setText("DASHBOARD");
        dashboardBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                dashboardBTNActionPerformed(evt);
            }
        });
        jPanel2.add(dashboardBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 240, 150, 40));

        roomsBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        roomsBTN.setText("ROOMS");
        roomsBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomsBTNActionPerformed(evt);
            }
        });
        jPanel2.add(roomsBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 320, 150, 40));

        bookingBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        bookingBTN.setText("BOOKING");
        bookingBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bookingBTNActionPerformed(evt);
            }
        });
        jPanel2.add(bookingBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 400, 150, 40));

        getContentPane().add(jPanel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 210, 750));

        dashboardPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel11.setFont(new java.awt.Font("Serif", 1, 100)); // NOI18N
        jLabel11.setText("HELLO!");
        dashboardPNL.add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, -1, -1));

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/dashborad.png"))); // NOI18N
        dashboardPNL.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, -1, -1));

        JTabbedPane.addTab("DASHBOARD", dashboardPNL);

        bookingsPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 48)); // NOI18N
        jLabel4.setText("BOOK NOW!");
        bookingsPNL.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 40, -1, -1));
        bookingsPNL.add(endDateJcalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 430, 200, 40));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel6.setText("Booking Record");
        bookingsPNL.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 140, -1, -1));

        jLabel7.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel7.setText("End Date");
        bookingsPNL.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 430, -1, 40));

        jLabel8.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel8.setText("Room Number");
        bookingsPNL.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 310, -1, 40));

        jLabel9.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel9.setText("Starting Date");
        bookingsPNL.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 370, -1, 40));

        BookBTN.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        BookBTN.setText("Book");
        BookBTN.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BookBTNActionPerformed(evt);
            }
        });
        bookingsPNL.add(BookBTN, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 510, 210, 50));

        jButton2.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jButton2.setText("Cancel Book");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        bookingsPNL.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 650, 210, 50));

        bookingTBL.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Booking ID", "Room ID", "Check in Date", "Status"
            }
        ));
        jScrollPane1.setViewportView(bookingTBL);

        bookingsPNL.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 180, -1, 520));

        jLabel10.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel10.setText("Room Type");
        bookingsPNL.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, -1, 40));
        bookingsPNL.add(startingdateJcalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 370, 200, 40));

        searchTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchTXTActionPerformed(evt);
            }
        });
        bookingsPNL.add(searchTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 180, 200, 40));

        roomNoTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomNoTXTActionPerformed(evt);
            }
        });
        bookingsPNL.add(roomNoTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 310, 200, 40));

        roomTypeTXT.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                roomTypeTXTActionPerformed(evt);
            }
        });
        bookingsPNL.add(roomTypeTXT, new org.netbeans.lib.awtextra.AbsoluteConstraints(240, 250, 200, 40));

        searchBtn.setText("Search");
        searchBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchBtnActionPerformed(evt);
            }
        });
        bookingsPNL.add(searchBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 180, -1, 40));

        updateBtn.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        updateBtn.setText("Update Booking");
        bookingsPNL.add(updateBtn, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 580, 210, 50));

        jLabel12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/BG.png"))); // NOI18N
        jLabel12.setText("jLabel12");
        bookingsPNL.add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, -1, -1));

        JTabbedPane.addTab("BOOKING", bookingsPNL);

        roomsPNL.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel3.setText("₱1200");
        roomsPNL.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, -1, -1));

        jLabel5.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel5.setText("₱3500");
        roomsPNL.add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(620, 110, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 36)); // NOI18N
        jLabel2.setText("₱2000");
        roomsPNL.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 110, -1, -1));

        bg.setFont(new java.awt.Font("Segoe UI", 3, 24)); // NOI18N
        bg.setIcon(new javax.swing.ImageIcon(getClass().getResource("/images/roomsbg.png"))); // NOI18N
        roomsPNL.add(bg, new org.netbeans.lib.awtextra.AbsoluteConstraints(-210, 0, -1, -1));

        JTabbedPane.addTab("ROOMS", roomsPNL);

        getContentPane().add(JTabbedPane, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, -30, 940, 780));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void logoutBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_logoutBTNActionPerformed
        Login loginFrame = new Login();
        this.setVisible(false);
        loginFrame.setVisible(true);
    }//GEN-LAST:event_logoutBTNActionPerformed

    private void dashboardBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_dashboardBTNActionPerformed
        JTabbedPane.setSelectedIndex(0);
    }//GEN-LAST:event_dashboardBTNActionPerformed

    private void roomsBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomsBTNActionPerformed
        JTabbedPane.setSelectedIndex(2);
    }//GEN-LAST:event_roomsBTNActionPerformed

    private void bookingBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bookingBTNActionPerformed
        JTabbedPane.setSelectedIndex(1);
    }//GEN-LAST:event_bookingBTNActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    private void searchTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_searchTXTActionPerformed

    private void roomNoTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomNoTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomNoTXTActionPerformed

    private void roomTypeTXTActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_roomTypeTXTActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_roomTypeTXTActionPerformed

    private void BookBTNActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BookBTNActionPerformed

    }//GEN-LAST:event_BookBTNActionPerformed

    private void searchBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchBtnActionPerformed
    // Get Booking ID from search field
    String bookingID = searchTXT.getText().trim();

    // Validate input (ensure it's not empty)
    if (bookingID.isEmpty()) {
        JOptionPane.showMessageDialog(null, "Please enter a Booking ID", "Warning", JOptionPane.WARNING_MESSAGE);
        return;
    }

    // SQL query to fetch booking details including room type
    String query = "SELECT b.bookingID, b.roomID, b.checkInDate, b.checkOutDate, r.roomType " +
                   "FROM booking b " +
                   "JOIN room r ON b.roomID = r.roomID " + // Join booking table with room table
                   "WHERE b.bookingID = ?";

    // Get the existing database connection
    Connection conn = DatabaseConnection.getInstance().getConnection();

    // Ensure connection is not null before proceeding
    if (conn == null) {
        JOptionPane.showMessageDialog(null, "Database connection error", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    try (PreparedStatement ps = conn.prepareStatement(query)) {
        ps.setString(1, bookingID); // Set the bookingID parameter
        ResultSet rs = ps.executeQuery();

        if (rs.next()) {
            // Fetch values from result set
            int fetchedRoomID = rs.getInt("roomID");
            String fetchedRoomType = rs.getString("roomType"); // Get room type
            Date startDate = rs.getDate("checkInDate");
            Date endDate = rs.getDate("checkOutDate");

            // Display roomType in searchTXT instead of roomTypeTXT
            roomTypeTXT.setText(fetchedRoomType); // Show roomType in search field
            roomNoTXT.setText(String.valueOf(fetchedRoomID));
            startingdateJcalendar.setDate(startDate);
            endDateJcalendar.setDate(endDate);

        } else {
            JOptionPane.showMessageDialog(null, "Booking not found", "Error", JOptionPane.ERROR_MESSAGE);
        }

    } catch (SQLException e) {
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error retrieving booking data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
    }//GEN-LAST:event_searchBtnActionPerformed
    
    public void loadSimpleBookingDataToTable() {
    // SQL query to fetch booking data (only bookingID, roomID, checkInDate, and status)
    String query = "SELECT bookingID, roomID, checkInDate, status FROM booking";

    // Get the existing database connection from the DatabaseConnection singleton
    Connection conn = DatabaseConnection.getInstance().getConnection();

    // Ensure the connection is not null before proceeding
    if (conn == null) {
        JOptionPane.showMessageDialog(null, "Unable to connect to the database", "Error", JOptionPane.ERROR_MESSAGE);
        return;
    }

    // Prepare the PreparedStatement and ResultSet to execute the query
    try (PreparedStatement ps = conn.prepareStatement(query);
         ResultSet rs = ps.executeQuery()) {

        // Create a DefaultTableModel to handle the table data
        DefaultTableModel model = (DefaultTableModel) bookingTBL.getModel();
        model.setRowCount(0); // Clear existing rows

        // Iterate over the result set and add rows to the table
        while (rs.next()) {
            int bookingID = rs.getInt("bookingID");
            int roomID = rs.getInt("roomID");
            Date checkInDate = rs.getDate("checkInDate");
            String status = rs.getString("status");

            // Add row to the table
            model.addRow(new Object[]{bookingID, roomID, checkInDate, status});
        }

    } catch (SQLException e) {
        // Log or handle the exception as needed
        e.printStackTrace();
        JOptionPane.showMessageDialog(null, "Error loading booking data: " + e.getMessage(), "Error", JOptionPane.ERROR_MESSAGE);
    }
}

    private void clearFields() {
    roomTypeTXT.setText("");  // Clear room type field
    roomNoTXT.setText("");    // Clear room number field
    searchTXT.setText("");    // Clear search field
    startingdateJcalendar.setDate(null); // Clear start date
    endDateJcalendar.setDate(null);      // Clear end date
}
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(User.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new User().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BookBTN;
    private javax.swing.JTabbedPane JTabbedPane;
    private javax.swing.JLabel bg;
    private javax.swing.JButton bookingBTN;
    private javax.swing.JTable bookingTBL;
    private javax.swing.JPanel bookingsPNL;
    private javax.swing.JButton dashboardBTN;
    private javax.swing.JPanel dashboardPNL;
    private de.wannawork.jcalendar.JCalendarComboBox endDateJcalendar;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel logoLBL;
    private javax.swing.JButton logoutBTN;
    private javax.swing.JTextField roomNoTXT;
    private javax.swing.JTextField roomTypeTXT;
    private javax.swing.JButton roomsBTN;
    private javax.swing.JPanel roomsPNL;
    private javax.swing.JButton searchBtn;
    private javax.swing.JTextField searchTXT;
    private de.wannawork.jcalendar.JCalendarComboBox startingdateJcalendar;
    private javax.swing.JButton updateBtn;
    // End of variables declaration//GEN-END:variables
}
